title: "My Professional Portfolio"
description: "Showcasing my AI, DevOps, Cloud, Automation, and Web projects"
theme: "minimal-mistakes-jekyll"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /:categories/:title/
collections:
  projects:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "single-project"
